---
title: 'S&DS363 Final Project Data'
author: "Yavuz Ramiz Çolak, Ryo Tamaki, Liana Wang, David Lieberman"
date: "March 27th, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
rm(list=ls())
options(warn=-1)
library(data.table)
library(Quandl)
```

DATA COLLECTION
```{r}
Quandl.api_key("LQ8syJ41h-Ar9UMq2M-N")
sp500 <- read.csv("https://pastebin.com/raw/ScRKxckW")
companies <- as.vector(as.character(sp500$Ticker))
sector <- as.vector(as.character(sp500$Sector))
data1 <- Quandl.datatable("SHARADAR/SF1",  ticker=companies[1:252], calendardate="2017-12-31")
data2 <- Quandl.datatable("SHARADAR/SF1",  ticker=companies[253:505], calendardate="2017-12-31")
data <- rbind(data1, data2)
data <- data[order(data$ticker),]

sector <- sector[companies %in% data$ticker]
data <- cbind(sector, data)
data <- data[,c(2,1,8:112)]
data <- data[ , apply(data, 2, function(x) !(length(which(is.na(x))) > 15))]
data <- na.omit(data)

# sink("outfile.txt")
# for (i in names(data)){
#   cat(i)
#   cat("\n")
# }
# sink()
```

PRICE DATA
```{r}
price_2018_1 <- Quandl.datatable("SHARADAR/SF1",  ticker=companies[1:252], calendardate="2018-12-31", qopts.columns=c("ticker", "price"))
price_2018_1 <- price_2018_1[order(price_2018_1$ticker),]
price_2018_2 <- Quandl.datatable("SHARADAR/SF1",  ticker=companies[253:505], calendardate="2018-12-31", qopts.columns=c("ticker", "price"))
price_2018_2 <- price_2018_2[order(price_2018_2$ticker),]
price_2018 <- rbind(price_2018_1, price_2018_2)


price_dataframe <- data.frame("ticker" = data$ticker, "price_2017" = data$price, "price_2018" = rep(NA, nrow(data)))
for (i in 1:nrow(data)){
  if (data$ticker[i] %in% price_2018$ticker){
      position_2018 <- which(price_2018$ticker == data$ticker[i])
      price_dataframe$price_2018[i] <- price_2018$price[position_2018]
  }
  else{
    price_dataframe$price_2018[i] <- NA
  }
}

missing <- as.vector(which(is.na(price_dataframe$price_2018)))
missing_ticker <- data$ticker[missing]
missing_prices <- c(NA, NA, NA, NA, NA, NA, 43.04, NA, 14.66, NA, 47.78, NA, 71.34, NA)

j <- 1
for (i in missing){
  price_dataframe$price_2018[i] <- missing_prices[j]
  j <- j + 1
}

missing <- as.vector(which(is.na(price_dataframe$price_2018)))

data <- data[-missing,]
price_dataframe <- price_dataframe[-missing,]

percent_change <- (price_dataframe$price_2018 - price_dataframe$price_2017)/price_dataframe$price_2018
sp500_percent <- (2506.85 - 2673.61)/2506.85
lower_percent_bound <- sp500_percent + 1.5*sp500_percent
upper_percent_bound <- sp500_percent - 1.5*sp500_percent

returns <- c()
for (i in 1:length(percent_change)){
  if (between(percent_change[i], lower_percent_bound, upper_percent_bound, incbounds=TRUE)){
    returns[i] <- "Mediocre"
  }
  else if (percent_change[i] > upper_percent_bound){
    returns[i] <- "High"
  }
  else{
    returns[i] <- "Low"
  }
}

price_dataframe <- cbind(price_dataframe, percent_change)
price_dataframe <- cbind(price_dataframe, returns)
setattr(price_dataframe, "row.names", as.vector(data$ticker))

price_dataframe
```

CONSTRUCTING OUR WORKING DATA
```{r}
equity_assets <- data$equity / data$assets
cashneq_liabilities <- data$cashneq / data$liabilities
ebit_ev <- data$ebit / data$ev
ev_ebitda <- data$ev / data$ebitda

working_data <- data.frame("ticker"=data$ticker, "sector"=data$sector, cashneq_liabilities, equity_assets, ebit_ev, ev_ebitda, "ebitdamargin"=data$ebitdamargin, "grossmargin"=data$grossmargin, "netmargin"=data$netmargin, "roa"=data$roa, "roe"=data$roe, "roic"=data$roic, "ros"=data$ros, "ev"=data$ev, "percent_change"=price_dataframe$percent_change, "returns"=price_dataframe$returns)
setattr(working_data, "row.names", as.vector(working_data$ticker))


remove <- c(which(working_data$sector %in% c("Telecommunication Services")), which(cashneq_liabilities <= 0))
working_data <- working_data[-remove,]

working_data$sector <- droplevels(working_data$sector)

working_data
```